visualize: 1
world_name: robotics_testlabs

sensors:
- name: top_kinect
  type: kinect
  source: /amigo/top_kinect/rgbd
  frame_id: /amigo/top_kinect/openni_rgb_optical_frame
  visualize: 0
  voxel_size: 0.02
  max_range: 2.0
  clearing_padding_fraction: 0.05
  normal_k_search: 15
  association_modules:
  - type: PointNormal
    parameters:
        association_correspondence_distance: 0.3
        position_weight: 2.0
        normal_weight: 1.0
        render_width: 320
        render_max_range: 2.2
        render_voxel_size: 0.02
        normal_k_search: 15
        visualize: 0
  - type: PolygonHeight
    parameters:
        max_range: 2.0
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0
  segmentation_modules:
  - type: EuclideanClustering
    parameters:
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0


